// Generated by https://quicktype.io

class Videos {
  List<Video> videos = new List();

  Videos.fromJsonList(List<dynamic> jsonList){
    if(jsonList == null) return;

    jsonList.forEach((item) {
      final video = Video.fromJsonMap(item);
      videos.add(video);
     });
  }
}

class Video {
  String id;
  String iso6391;
  String iso31661;
  String key;
  String name;
  String site;
  int size;
  String type;

  Video({
    this.id,
    this.iso6391,
    this.iso31661,
    this.key,
    this.name,
    this.site,
    this.size,
    this.type,
  });

   Video.fromJsonMap(Map<String, dynamic> json){
    this.id         = json['id'];
    this.iso6391    = json['iso_639_1'];
    this.iso31661   = json['iso_3166_1'];
    this.key        = json['key'];
    this.name       = json['name'];
    this.site       = json['site'];
    this.size       = json['size'];
    this.type       = json['type'];
  }
}
